"""One-time resolution of the Rust branch against the pinned TypeScript merge."""
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = "53b9b86956c963fbed74cb5cf84c66fff6503fa5"


def git(*args, check=True):
    return subprocess.run(["git", *args], cwd=ROOT, text=True, capture_output=True, check=check)


def change(path, before, after):
    file = ROOT / path
    text = file.read_text()
    if before not in text:
        raise RuntimeError(f"Expected source changed in {path}: {before[:100]!r}")
    file.write_text(text.replace(before, after))


head = git("rev-parse", "HEAD").stdout.strip()
base = git("merge-base", head, TARGET).stdout.strip()
if base == TARGET:
    raise RuntimeError("The target is already merged; do not repeat this migration.")
ours = set(git("diff", "--name-only", base, head).stdout.splitlines())
theirs = set(git("diff", "--name-only", base, TARGET).stdout.splitlines())
merge = git("merge", "--no-commit", "--no-ff", TARGET, check=False)
print(merge.stdout, merge.stderr)
if merge.returncode not in (0, 1):
    raise RuntimeError("Git merge failed before conflict resolution")
# Adopt the merged language interfaces and port Rust below. Unique files on
# either side and unrelated changes remain in the ordinary three-way merge.
shared = sorted(ours & theirs)
if shared:
    git("restore", "--source=" + TARGET, "--staged", "--worktree", "--", *shared)
if git("diff", "--name-only", "--diff-filter=U").stdout.strip():
    raise RuntimeError("Unexpected unresolved path outside the shared integration surface")
print("Reconciled shared paths:", "\n".join(shared))

# One classifier for all languages; retain TS extension, test, header and config
# rules while adding Rust. No competing Go/Rust-only classifier remains.
path = "adapters/opencode/lib/source-files.ts"
change(path, '"pnpm-lock.yaml", "yarn.lock", "bun.lock",', '"pnpm-lock.yaml", "yarn.lock", "bun.lock",\n  "Cargo.toml", "Cargo.lock", "rust-toolchain", "rust-toolchain.toml",\n  "clippy.toml", ".clippy.toml", "rustfmt.toml", ".rustfmt.toml",')
change(path, 'export function sourceLanguage(path: string): "Go" | "TypeScript" | undefined {', 'export type SourceLanguage = "Go" | "TypeScript" | "Rust";\n\nexport function sourceLanguage(path: string): SourceLanguage | undefined {')
change(path, '  if (path.endsWith(".go")) return "Go";', '  if (path.endsWith(".go")) return "Go";\n  if (path.endsWith(".rs")) return "Rust";')
change(path, '  if (sourceLanguage(path) !== "TypeScript") return false;\n  return typeScriptTest', '  if (sourceLanguage(path) === "Rust") return path.split("/").slice(0, -1).some(part => ["tests", "benches"].includes(part));\n  if (sourceLanguage(path) !== "TypeScript") return false;\n  return typeScriptTest')
change(path, '  return path.endsWith(".md") || contextNames.has(name) ||', '  return path.endsWith(".md") || contextNames.has(name) ||\n    (path.split("/").at(-2) === ".cargo" && ["config", "config.toml"].includes(name)) ||')
change(path, 'export function isGeneratedSource(path: string, content: string): boolean {', '''export function isBuildOutput(path: string): boolean {
  return sourceLanguage(path) === "Rust" && path.split("/").slice(0, -1).includes("target");
}

export function isReadableSource(path: string): boolean {
  return (Boolean(sourceLanguage(path)) || isReadableContext(path)) &&
    !isInternalPath(path) && !isTestSource(path) && !isBuildOutput(path);
}

// Path/header filtering does not parse Rust items or resolve Cargo targets.
export const rustScopeNote = "Rust paths and known generated headers are filtered, not Rust items or Cargo targets. Use manifest/declaration context to exclude custom test/benchmark targets and test-only items in mixed files; incidental test search matches do not establish reviewed coverage.";

export function isGeneratedSource(path: string, content: string): boolean {''')
change(path, '  if (sourceLanguage(path) !== "TypeScript") return false;\n  // Recognize', '  if (!["TypeScript", "Rust"].includes(sourceLanguage(path) ?? "")) return false;\n  // Recognize')
change(path, '  return /(?:@generated', '  if (sourceLanguage(path) === "Rust") return /(?:@generated\\b|automatically generated by rust-bindgen\\b)/.test(header);\n  return /(?:@generated')
(ROOT / "adapters/opencode/lib/languages.ts").unlink()

path = "adapters/opencode/lib/github.ts"
change(path, 'isTestSource, isReadableContext, isGeneratedSource', 'isTestSource, isReadableSource, isGeneratedSource, isBuildOutput, rustScopeNote, type SourceLanguage')
change(path, 'type ChangedFile = { path: string;', 'type ChangedFile = { path: string; language?: SourceLanguage;')
change(path, '  if (isTestSource(path)) return "test file";', '  if (isTestSource(path)) return "test file";\n  if (isBuildOutput(path)) return "Rust build-output path";')
change(path, '      exclusion: exclusion(f.filename, f.status),', '      exclusion: exclusion(f.filename, f.status),\n      language: sourceLanguage(f.filename),')
change(path, '    const allowed = Boolean(sourceLanguage(path)) || isReadableContext(path);\n    if (!allowed || isTestSource(path) || isInternalPath(path)) {', '    if (!isReadableSource(path)) {')
change(path, 'Only non-test Go/TypeScript,', 'Only eligible Go/TypeScript/Rust source,')
change(path, '      path, revision, commit: ref, blob: entry.sha, exists: true,', '      path, revision, commit: ref, blob: entry.sha, exists: true,\n      language: sourceLanguage(path), scopeNote: sourceLanguage(path) === "Rust" ? rustScopeNote : undefined,')
change(path, '      commit: snapshot.H, literal: needle, prefix,', '      commit: snapshot.H, literal: needle, prefix,\n      scopeNote: page.some(entry => sourceLanguage(entry.path) === "Rust") ? rustScopeNote : undefined,')

lenses = ["naming", "control-flow", "function-cohesion", "data-flow", "abstractions", "duplication", "api-clarity", "change-locality", "representation", "rationale"]
profiles = ["lifecycle-ownership", "dependency-boundaries", "effects-separation", "error-expression"]
resources = ["references/languages/rust.md"] + [f"references/lenses/rust/{name}.md" for name in lenses] + [f"references/profiles/rust/{name}.md" for name in profiles]
change("adapters/opencode/tools/super_review.ts", '  "assets/finding-template.md",', ''.join(f'  "{path}",\n' for path in resources) + '  "assets/finding-template.md",')

# Keep shared routing in languages.md, not language-specific host instructions.
paths = ["README.md", "package.json", "plugin.json", ".codex-plugin/plugin.json", "skills/super-review/SKILL.md", "skills/super-review/agents/openai.yaml", "skills/super-review/references/review-contract.md", "skills/super-review/references/team-rules.md", "skills/super-review/references/workflow.md", "skills/super-review/references/verification.md", "src/mcp.ts", "adapters/opencode/tools/super_review.ts"]
paths += [str(p.relative_to(ROOT)) for folder in ["adapters/claude", "adapters/opencode/agents", "adapters/opencode/commands", "skills/super-review/references/harnesses"] for p in (ROOT / folder).glob("*.md")]
for path in paths:
    file = ROOT / path
    text = file.read_text()
    for before, after in [("Go and TypeScript", "Go, TypeScript, and Rust"), ("Go or TypeScript", "Go, TypeScript, or Rust"), ("Go/TypeScript", "Go/TypeScript/Rust")]:
        text = text.replace(before, after)
    file.write_text(text)
change("skills/super-review/agents/openai.yaml", "Go/Rust", "Go/TypeScript/Rust")
change("skills/super-review/agents/openai.yaml", "Go or Rust", "Go, TypeScript, or Rust")
change("adapters/opencode/tools/super_review.ts", "Search a literal in non-test Go, TypeScript, and Rust source", "Search a literal in candidate Go/TypeScript/Rust source")
change("adapters/opencode/tools/super_review.ts", "20 files per call. Follow nextOffset to finish a scope;", "20 files per call. Rust item/test scope still requires declaration context. Follow nextOffset to finish a scope;")
file = ROOT / "src/mcp.ts"
text = re.sub(r'Find one literal substring[^"\n]+', 'Find one literal substring in candidate Go/TypeScript/Rust source at H, 20 files per page. Rust item/test scope still requires declaration context. Follow nextOffset for required remaining context.', file.read_text())
file.write_text(text)

path = "skills/super-review/references/languages.md"
change(path, "Do not translate Go-specific advice into TypeScript or load both implementations", "Do not translate language-specific advice across languages or load every implementation")
change(path, "| TypeScript | `.ts`", "| Rust | `.rs` | [Rust](languages/rust.md) |\n| TypeScript | `.ts`")
change(path, "Existing `go.*` IDs retain their meaning; TypeScript uses separate `ts.*` IDs.", "Existing `go.*` and `ts.*` IDs retain their meaning; Rust uses separate `rust.*` IDs.")
file = ROOT / path
text = file.read_text()
for name in lenses:
    old = f"| [TS](lenses/typescript/{name}.md) |"
    text = text.replace(old, old + f" [Rust](lenses/rust/{name}.md) |")
for name in profiles:
    old = f"| [TS](profiles/typescript/{name}.md) |"
    text = text.replace(old, old + f" [Rust](profiles/rust/{name}.md) |")
text = text.replace("| Lens | Go | TypeScript |\n| --- | --- | --- |", "| Lens | Go | TypeScript | Rust |\n| --- | --- | --- | --- |")
text = text.replace("| Profile | Owner | Go | TypeScript |\n| --- | --- | --- | --- |", "| Profile | Owner | Go | TypeScript | Rust |\n| --- | --- | --- | --- | --- |")
text = text.replace("inspect translation or failure-path structure. Profiles retain", "inspect translation or failure-path structure. Rust's ordinary `?` alone is also\ninsufficient; inspect translation, recovery or failure-path structure. Profiles retain")
text = text.replace("## Lens resources", "Rust crate/workspace manifests establish edition, MSRV, target and feature context\nunder [Rust context](languages/rust.md). Exclude Rust test-only targets/items and\nknown generated source, but retain production declarations in mixed files. Reader\npath/header filtering does not establish item-level coverage.\n\n## Lens resources")
file.write_text(text)
file = ROOT / "skills/super-review/references/languages/rust.md"
text = file.read_text()
start, end = text.index("## Language-specific modules"), text.index("Background:")
file.write_text(text[:start] + "Use [language routing](../languages.md) to select the Rust implementation of the\nassigned lens and owner profiles. The shared workflow owns coverage; these are\nnot extra workers or a mandatory all-module packet.\n\n" + text[end:])
change("skills/super-review/references/workflow.md", "mandatory resources for TypeScript.", "mandatory resources for TypeScript or Rust.")
change("skills/super-review/references/review-contract.md", "directories), generated files,", "directories; Rust test-only targets and items), generated files,")
change("skills/super-review/references/review-contract.md", "Review changed Go, TypeScript, and Rust source and", "Review changed Go, TypeScript, and Rust production source and")
change("skills/super-review/references/team-rules.md", "override cannot disable or replace a TS default, or vice versa.", "override cannot disable or replace a TS default, or vice versa. Rust rules use\n`Language: Rust` and their `rust.*` headings. All three namespaces are independent;\na language's override/disable follows only its own owner rule into profiles.")
change("skills/super-review/references/verification.md", "Do not infer equivalence", "For Rust, inspect implicated trait/auto-trait contracts, ownership, eager/lazy\nevaluation and guard/drop lifetimes under the selected language context.\nDo not infer equivalence")

path = "README.md"
change(path, "Go, TypeScript, and Rust (`.ts`, `.tsx`, `.mts`, `.cts`, including handwritten declaration\nfiles) use", "Go, TypeScript (`.ts`, `.tsx`, `.mts`, `.cts`, including handwritten declaration\nfiles), and Rust (`.rs`) use")
change(path, "Mixed PRs are partitioned by language; Go rules are not applied to TS.", "Mixed PRs are partitioned by language; each language keeps its own rules.")
change(path, "for judgment, boundaries, and evaluation limits.", "and [Rust support](docs/rust-review.md) for judgment, boundaries, and evaluation limits.")
change(path, "`Action: refine ts.abstractions.earn-the-boundary`; existing Go IDs do not change.", "`Action: refine ts.abstractions.earn-the-boundary`; existing Go IDs do not change.\nRust rules use `Language: Rust` and `rust.*` IDs; see the\n[Rust convention example](examples/team-rules/RUST.md).")
file = ROOT / "docs/rust-review.md"
text = file.read_text().replace("Mixed PRs retain both language scopes.", "Mixed Go/TypeScript/Rust PRs retain every included language scope through the\n[shared routing catalog](../skills/super-review/references/languages.md).")
text += "\nThe shared file classifier is `adapters/opencode/lib/source-files.ts`; Rust uses\nthe same inventory/read/search path as Go and TypeScript, not a second classifier.\n"
file.write_text(text)
file = ROOT / "CHANGELOG.md"
text = file.read_text()
notes = "- Add Rust-specific review lenses/profiles and 11 stable `rust.*` rules without changing Go or TypeScript IDs.\n- Integrate Rust source/Cargo context into shared Go/TypeScript routing and classification; preserve test/generated-code scope limits.\n- Add Rust evaluation packets and mixed-language regression tests; live model quality remains unevaluated.\n"
if "## Unreleased\n" in text:
    text = text.replace("## Unreleased\n", "## Unreleased\n\n" + notes, 1)
elif "## [Unreleased]\n" in text:
    text = text.replace("## [Unreleased]\n", "## [Unreleased]\n\n" + notes, 1)
else:
    first, rest = text.split("\n", 1)
    text = first + "\n\n## Unreleased\n\n" + notes + rest
file.write_text(text)
file = ROOT / "plugin.json"
data = json.loads(file.read_text())
for keyword in ["typescript", "rust"]:
    if keyword not in data["keywords"]:
        data["keywords"].append(keyword)
file.write_text(json.dumps(data, indent=2) + "\n")

file = ROOT / "scripts/validate.ts"
text = file.read_text().replace(r"/^## (go\.[a-z0-9.-]+)$/gm", r"/^## ((?:go|ts|rust)\.[a-z0-9.-]+)$/gm")
start, end = text.index("if (ids.size === 0)"), text.index("for (const role of")
text = text[:start] + '''for (const [language, prefix] of [["go", "go"], ["typescript", "ts"], ["rust", "rust"]]) {
  const expected: string[] = JSON.parse(await readFile(join(root, "evals/" + language + "/rule-ids.json"), "utf8"));
  const actual = [...ids].filter(id => id.startsWith(prefix + ".")).sort();
  if (!actual.length || JSON.stringify(actual) !== JSON.stringify(expected.sort())) errors.push(language + " rule IDs changed: document migration and update the manifest intentionally.");
}
''' + text[end:]
file.write_text(text)

path = "tests/rust-support.test.ts"
change(path, 'import { GitHubReader }', 'import { GitHubReader, exclusion }')
change(path, 'import { exclusion, generatedSource, readableSource } from "../adapters/opencode/lib/languages.ts";', 'import { isGeneratedSource as generatedSource, isReadableSource as readableSource } from "../adapters/opencode/lib/source-files.ts";')
change(path, 'language: "rust"', 'language: "Rust"')
# Only the now-supported Rust negative case changes; all TS regression checks stay.
change("tests/typescript.test.ts", '"a.ts.bak", "a.rs", "package.json"', '"a.ts.bak", "package.json"')
change("tests/typescript.test.ts", 'expect(sourceLanguage("a.go")).toBe("Go");', 'expect(sourceLanguage("a.go")).toBe("Go");\n    expect(sourceLanguage("a.rs")).toBe("Rust");\n    expect(exclusion("a.rs")).toBeUndefined();')
print("Integrated Rust into the merged TypeScript language architecture.")
