// Mechanical path/header classification only. Rust item and Cargo target scope
// belongs to the review instructions; do not pretend regexes parse that syntax.
export type SourceLanguage = "go" | "rust";

export function sourceLanguage(path: string): SourceLanguage | undefined {
  if (path.endsWith(".go")) return "go";
  if (path.endsWith(".rs")) return "rust";
  return undefined;
}

function blockedPath(path: string): boolean {
  return path.split("/").some(part => ["vendor", "node_modules", ".git"].includes(part));
}

function rustExcludedPath(path: string): boolean {
  return path.endsWith(".rs") && path.split("/").some(part => ["tests", "benches", "target"].includes(part));
}

export function exclusion(path: string, status?: string): string | undefined {
  if (status === "removed") return "deleted file: no head source";
  if (blockedPath(path)) return "vendored or repository internals";
  if (path.endsWith("_test.go")) return "test file";
  if (rustExcludedPath(path)) return "Rust test, benchmark, or build-output path";
  if (!sourceLanguage(path)) return "unsupported language or non-source file";
  return undefined;
}

const contextNames = new Set([
  "go.mod", "Cargo.toml", "Cargo.lock", "rust-toolchain", "rust-toolchain.toml",
  "clippy.toml", ".clippy.toml", "rustfmt.toml", ".rustfmt.toml",
]);

export function readableSource(path: string): boolean {
  if (blockedPath(path)) return false;
  if (sourceLanguage(path)) return !exclusion(path);
  const parts = path.split("/");
  const name = parts.at(-1)!;
  return path.endsWith(".md") || contextNames.has(name) ||
    (parts.at(-2) === ".cargo" && ["config", "config.toml"].includes(name));
}

export function generatedSource(path: string, content: string): boolean {
  if (path.endsWith(".go")) return /^\/\/ Code generated .* DO NOT EDIT\.$/m.test(content);
  if (!path.endsWith(".rs")) return false;
  // Recognize a leading generator declaration, not mentions inside Rust code.
  return /^\s*(?:\/\/[^\n]*@generated\b|\/\*\s*automatically generated by rust-bindgen\b)/.test(content);
}

export const rustScopeNote = "Rust paths and known generated headers are filtered, not Rust items or Cargo targets. Use manifest/declaration context to exclude custom test/benchmark targets and test-only items in mixed files; incidental test search matches do not establish reviewed coverage.";
