// Shared file classification for the inventory, source reader, and caller search.
// Configuration is readable context, not a review target or executable input.
const typeScriptExtension = /\.(?:ts|tsx|mts|cts)$/;
const typeScriptTest = /\.(?:test|spec)\.(?:ts|tsx|mts|cts)$/;
const testDirectories = new Set(["test", "tests", "__tests__", "__mocks__", "__snapshots__"]);
const contextNames = new Set([
  "go.mod", "package.json", "package-lock.json", "npm-shrinkwrap.json",
  "pnpm-lock.yaml", "yarn.lock", "bun.lock",
  "Cargo.toml", "Cargo.lock", "rust-toolchain", "rust-toolchain.toml",
  "clippy.toml", ".clippy.toml", "rustfmt.toml", ".rustfmt.toml",
]);

export type SourceLanguage = "Go" | "TypeScript" | "Rust";

export function sourceLanguage(path: string): SourceLanguage | undefined {
  if (path.endsWith(".go")) return "Go";
  if (path.endsWith(".rs")) return "Rust";
  if (typeScriptExtension.test(path)) return "TypeScript";
  return undefined;
}

export function isInternalPath(path: string): boolean {
  return path.split("/").some(part => ["vendor", "node_modules", ".git"].includes(part));
}

export function isTestSource(path: string): boolean {
  if (path.endsWith("_test.go")) return true;
  if (sourceLanguage(path) === "Rust") return path.split("/").slice(0, -1).some(part => ["tests", "benches"].includes(part));
  if (sourceLanguage(path) !== "TypeScript") return false;
  return typeScriptTest.test(path) || path.split("/").slice(0, -1).some(part => testDirectories.has(part));
}

export function isReadableContext(path: string): boolean {
  const name = path.split("/").at(-1)!;
  return path.endsWith(".md") || contextNames.has(name) ||
    (path.split("/").at(-2) === ".cargo" && ["config", "config.toml"].includes(name)) ||
    /^tsconfig(?:\.[A-Za-z0-9_-]+)*\.jsonc?$/.test(name) ||
    /^[A-Za-z0-9_.-]+\.tsconfig\.jsonc?$/.test(name);
}

export function isBuildOutput(path: string): boolean {
  return sourceLanguage(path) === "Rust" && path.split("/").slice(0, -1).includes("target");
}

export function isReadableSource(path: string): boolean {
  return (Boolean(sourceLanguage(path)) || isReadableContext(path)) &&
    !isInternalPath(path) && !isTestSource(path) && !isBuildOutput(path);
}

// Path/header filtering does not parse Rust items or resolve Cargo targets.
export const rustScopeNote = "Rust paths and known generated headers are filtered, not Rust items or Cargo targets. Use manifest/declaration context to exclude custom test/benchmark targets and test-only items in mixed files; incidental test search matches do not establish reviewed coverage.";

export function isGeneratedSource(path: string, content: string): boolean {
  if (sourceLanguage(path) === "Go") return /^\/\/ Code generated .* DO NOT EDIT\.$/m.test(content);
  if (!["TypeScript", "Rust"].includes(sourceLanguage(path) ?? "")) return false;
  // Recognize markers in leading comments only, not strings or examples in code.
  const header = /^(?:\uFEFF)?(?:#![^\n]*\n)?\s*((?:(?:\/\/[^\n]*(?:\n|$)|\/\*[\s\S]*?\*\/)\s*)*)/.exec(content)?.[1] ?? "";
  if (sourceLanguage(path) === "Rust") return /(?:@generated\b|automatically generated by rust-bindgen\b)/.test(header);
  return /(?:@generated\b|\bCode generated\b[^\n]*\bDO NOT EDIT\b|\bauto[- ]generated\b)/i.test(header);
}
