import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { createHash } from "node:crypto";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { GitHubReader, exclusion } from "../adapters/opencode/lib/github.ts";
import { sourceLanguage, isInternalPath, isReadableContext, isGeneratedSource } from "../adapters/opencode/lib/source-files.ts";
import { resource } from "../adapters/opencode/tools/super_review.ts";
import { createServer } from "../src/mcp.ts";

const root = resolve(import.meta.dir, "..");
const skill = resolve(root, "skills/super-review");
const read = (path: string) => readFileSync(resolve(skill, path), "utf8");
const lenses = ["naming", "control-flow", "function-cohesion", "data-flow", "abstractions", "duplication", "api-clarity", "change-locality", "representation", "rationale"];
const owners: Record<string, string> = { "lifecycle-ownership": "data-flow", "dependency-boundaries": "abstractions", "effects-separation": "function-cohesion", "error-expression": "control-flow" };
const paths = ["references/languages.md", "references/languages/java.md", ...lenses.map(lens => `references/lenses/java/${lens}.md`), ...Object.keys(owners).map(profile => `references/profiles/java/${profile}.md`)];

describe("Java acquisition and resource wiring (not model judgment)", () => {
  test("accepts production source without treating Test in a name as a test", () => {
    for (const path of ["Example.java", "module/src/main/java/TestFactory.java", "module/src/main/java/Contest.java", "module-info.java", "main.go"]) {
      expect(exclusion(path)).toBeUndefined();
      expect(sourceLanguage(path)).toBeDefined();
    }
    expect(exclusion("Example.java", "removed")).toContain("deleted");
  });

  test("excludes known tests, generated roots, internals, and unsupported languages", () => {
    for (const path of ["a_test.go", "src/test/java/A.java", "module/src/testFixtures/java/A.java", "src/integrationTest/java/A.java", "src/androidTest/java/A.java", "target/generated-sources/A.java", "build/generated/sources/A.java", "vendor/A.java", "node_modules/A.java", ".git/A.java", "Example.class", "Example.kt", "script.js"]) {
      expect(exclusion(path)).toBeDefined();
    }
  });

  test("allows build metadata only as supporting context", () => {
    for (const path of ["pom.xml", "parent/pom.xml", "build.gradle", "build.gradle.kts", "settings.gradle.kts", "gradle.properties", "gradle/libs.versions.toml", "build-logic/java-conventions.gradle.kts", "go.mod", "SUPER_REVIEW.md"]) {
      expect(isReadableContext(path)).toBe(true);
      expect(exclusion(path)).toBeDefined();
    }
    expect(isReadableContext("arbitrary.xml")).toBe(false);
    expect(isInternalPath(".git/config.md")).toBe(true);
  });

  test("generated detection is restricted to file headers for Java", () => {
    expect(isGeneratedSource("A.java", "// Generated by a tool. DO NOT EDIT!\nclass A {}" )).toBe(true);
    expect(isGeneratedSource("A.java", "\uFEFF/* Generated source.\n * Do not edit. */\npackage p; class A {}" )).toBe(true);
    expect(isGeneratedSource("A.java", 'class A { String help = "Generated. DO NOT EDIT"; }')).toBe(false);
    expect(isGeneratedSource("A.java", "class A {\n // Generated. DO NOT EDIT\n void method() {}\n}" )).toBe(false);
    expect(isGeneratedSource("A.java", "class A { @Generated(\"tool\") void method() {} }" )).toBe(false);
    expect(isGeneratedSource("a.go", "// Code generated by tool DO NOT EDIT.\npackage p" )).toBe(true);
  });

  test("Java flows through pinned inventory, source, diff and search", async () => {
    const B = "b".repeat(40), H = "a".repeat(40), D = "d".repeat(40);
    const texts: Record<string, string> = {
      "Example.ts": "export const needle = 1;\n",
      "Example.java": "class Example { String value = \"needle\"; }\n",
      "Generated.java": "// Generated by tool. DO NOT EDIT!\nclass Generated { String value = \"needle\"; }\n",
      "main.go": "package main\nconst needle = 1\n",
      "src/test/java/Hidden.java": "class Hidden { String needle; }\n",
      "pom.xml": "<project><properties><maven.compiler.release>17</maven.compiler.release></properties></project>\n",
    };
    const entries = Object.entries(texts).map(([path, text]) => ({ path, mode: "100644", type: "blob", sha: createHash("sha1").update(text).digest("hex"), size: Buffer.byteLength(text) }));
    const calls: string[] = [];
    const reader = new GitHubReader(async endpoint => {
      calls.push(endpoint);
      if (endpoint.endsWith("/pulls/1")) return { base: { sha: B, repo: { full_name: "o/r" } }, head: { sha: H, repo: { full_name: "o/r" } }, state: "open", draft: false };
      if (endpoint.includes("/compare/")) return { merge_base_commit: { sha: D }, files: entries.map(e => ({ filename: e.path, status: "modified", patch: "@@ -1 +1 @@\n+needle" })) };
      if (endpoint.includes("/git/trees/")) return { tree: entries, truncated: false };
      const entry = entries.find(e => endpoint.endsWith("/git/blobs/" + e.sha));
      if (entry) return { encoding: "base64", size: entry.size, content: Buffer.from(texts[entry.path]!).toString("base64") };
      throw new Error("Unexpected endpoint: " + endpoint);
    });
    const snapshot = await reader.pin("https://github.com/o/r/pull/1");
    expect(snapshot.files.find(f => f.path === "Example.java")?.exclusion).toBeUndefined();
    expect(snapshot.files.find(f => f.path === "src/test/java/Hidden.java")?.exclusion).toBeDefined();
    expect(await reader.source(snapshot.id, "head", "Example.java")).toMatchObject({ content: expect.stringContaining("needle") });
    expect(await reader.source(snapshot.id, "head", "pom.xml")).toMatchObject({ content: expect.stringContaining("17") });
    expect((await reader.source(snapshot.id, "head", "Generated.java")).excluded).toBe(true);
    const count = calls.length;
    expect((await reader.source(snapshot.id, "head", "src/test/java/Hidden.java")).excluded).toBe(true);
    expect(calls.length).toBe(count);
    expect(reader.diff(snapshot.id, "Example.java").available).toBe(true);
    const found = await reader.search(snapshot.id, "needle");
    expect(found.matches.map(m => m.path)).toEqual(["Example.java", "Example.ts", "main.go"]);
    expect(found.unread.map(f => f.path)).toEqual(["Generated.java"]);
    expect(found.scanned).not.toContain("pom.xml");
    expect(found.scanned).not.toContain("src/test/java/Hidden.java");
  });

  test("language-specific rules and owner profiles retain stable identities", () => {
    const ids: string[] = JSON.parse(readFileSync(resolve(root, "evals/java/rule-ids.json"), "utf8"));
    const actual = lenses.flatMap(lens => [...read(`references/lenses/java/${lens}.md`).matchAll(/^## (java\.[a-z0-9.-]+)$/gm)].map(match => match[1]!));
    expect(new Set(actual).size).toBe(actual.length);
    expect(actual.sort()).toEqual([...ids].sort());
    for (const [profile, owner] of Object.entries(owners)) {
      const text = read(`references/profiles/java/${profile}.md`);
      expect(/^Owner: (.+)$/m.exec(text)?.[1]).toBe(owner);
      const id = /^Rule: (java\.[a-z0-9.-]+)$/m.exec(text)?.[1];
      expect(id).toBeDefined();
      expect(read(`references/lenses/java/${owner}.md`)).toContain("## " + id);
      expect(text).not.toMatch(/^## (?:java|go)\./m);
    }
    for (const path of paths) expect(resource.args.path.safeParse(path).success).toBe(true);
    expect(resource.args.path.safeParse("evals/java/cases.json").success).toBe(false);
    expect(resource.args.path.safeParse("../../auth.json").success).toBe(false);
    expect(read("references/workflow.md")).toContain("languages.md");
    expect(read("SKILL.md")).toContain("references/languages.md");
  });

  for (const relativeRoot of ["skills/super-review", "adapters/claude/plugin/resources/super-review", "adapters/codex/super-review/skills/super-review"]) {
    test("serves byte-identical Java resources without loading evaluation answers: " + relativeRoot, async () => {
      const server = await createServer(resolve(root, relativeRoot));
      const client = new Client({ name: "java-resource-test", version: "1" });
      const [serverTransport, clientTransport] = InMemoryTransport.createLinkedPair();
      try {
        await server.connect(serverTransport);
        await client.connect(clientTransport);
        for (let offset = 0; offset < paths.length; offset += 8) {
          const selected = paths.slice(offset, offset + 8);
          const response = await client.callTool({ name: "resources", arguments: { paths: selected } });
          expect(response.isError).not.toBe(true);
          const content = response.content as Array<{ type: string; text: string }>;
          const payload = JSON.parse(content[0]!.text) as { resources: Array<{ path: string; content: string }> };
          expect(payload.resources.map(item => item.path)).toEqual(selected);
          for (const item of payload.resources) expect(item.content).toBe(read(item.path));
        }
        const denied = await client.callTool({ name: "resources", arguments: { paths: ["evals/java/cases.json"] } });
        expect(denied.isError).toBe(true);
      } finally {
        await client.close();
        await server.close();
      }
    });
  }

  test("evaluation rubric references neutral, uniquely identified packet sections", () => {
    const suite = JSON.parse(readFileSync(resolve(root, "evals/java/cases.json"), "utf8")) as { cases: Array<{ id: string; lens: string; expect: string[] }> };
    const packet = readFileSync(resolve(root, "evals/java/packets/idioms.md"), "utf8");
    const sections = [...packet.matchAll(/^## (J\d+)$/gm)].map(match => match[1]!);
    expect(new Set(sections).size).toBe(sections.length);
    expect(sections.sort()).toEqual(suite.cases.map(item => item.id).sort());
    for (const item of suite.cases) {
      expect(lenses).toContain(item.lens);
      expect(item.expect.length).toBeGreaterThan(0);
    }
  });
});
