import { describe, expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { readFileSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { GitHubReader } from "../adapters/opencode/lib/github.ts";
import { exclusion, generatedSource, readableSource } from "../adapters/opencode/lib/languages.ts";
import { createServer } from "../src/mcp.ts";
import { resource } from "../adapters/opencode/tools/super_review.ts";

const root = resolve(import.meta.dir, "..");
const skill = resolve(root, "skills/super-review");
const read = (path: string) => readFileSync(resolve(skill, path), "utf8");
const B = "a".repeat(40), H = "b".repeat(40), D = "c".repeat(40);
const hash = (text: string) => createHash("sha1").update(text).digest("hex");

function fixture(files: Record<string, string>) {
  const data = new Map<string, any>();
  const calls: string[] = [];
  const entries: any[] = [];
  const tree = (ref: string) => {
    const key = "repos/author/app/git/trees/" + ref;
    if (!data.has(key)) data.set(key, { tree: [] });
    return data.get(key).tree as any[];
  };
  for (const [path, content] of Object.entries(files)) {
    const parts = path.split("/");
    let parent = H;
    for (let i = 0; i < parts.length - 1; i++) {
      const sha = hash("directory:" + parts.slice(0, i + 1).join("/"));
      if (!tree(parent).some(e => e.path === parts[i])) tree(parent).push({ path: parts[i], type: "tree", mode: "040000", sha });
      parent = sha;
    }
    const sha = hash(content);
    const entry = { path: parts.at(-1), type: "blob", mode: "100644", sha, size: Buffer.byteLength(content) };
    tree(parent).push(entry);
    entries.push({ ...entry, path });
    data.set("repos/author/app/git/blobs/" + sha, { encoding: "base64", size: entry.size, content: Buffer.from(content).toString("base64") });
  }
  const info = { base: { sha: B, repo: { full_name: "acme/app" } }, head: { sha: H, repo: { full_name: "author/app" } }, state: "open", draft: false };
  data.set("repos/acme/app/pulls/1", info);
  data.set("repos/acme/app/compare/" + B + "..." + H, { merge_base_commit: { sha: D }, files: Object.keys(files).map(filename => ({ filename, status: "modified", patch: "@@ -0,0 +1 @@\n+source" })) });
  data.set("repos/author/app/git/trees/" + H + "?recursive=1", { tree: entries });
  const reader = new GitHubReader(async endpoint => {
    calls.push(endpoint);
    if (!data.has(endpoint)) throw new Error("Unexpected endpoint " + endpoint);
    return data.get(endpoint);
  });
  return { reader, calls, info };
}
const url = "https://github.com/acme/app/pull/1";

const lenses = ["naming", "control-flow", "function-cohesion", "data-flow", "abstractions", "duplication", "api-clarity", "change-locality", "representation", "rationale"];
const profiles = ["lifecycle-ownership", "dependency-boundaries", "effects-separation", "error-expression"];
const resources = ["references/languages/rust.md", ...lenses.map(name => "references/lenses/rust/" + name + ".md"), ...profiles.map(name => "references/profiles/rust/" + name + ".md")];

describe("Rust support: mechanical checks, not model evaluation", () => {
  test("source and context allowlists preserve exclusions without allowing arbitrary configuration", () => {
    for (const path of ["src/lib.rs", "crates/app/src/main.rs", "worker.go"]) expect(exclusion(path)).toBeUndefined();
    for (const path of ["tests/smoke.rs", "crates/app/benches/run.rs", "target/out.rs", "vendor/x.rs", "x_test.go", "x.py"]) expect(exclusion(path)).toBeDefined();
    expect(exclusion("src/old.rs", "removed")).toContain("deleted");
    for (const path of ["Cargo.toml", "crates/a/Cargo.toml", "Cargo.lock", "rust-toolchain", "rust-toolchain.toml", ".cargo/config.toml", "crates/a/.cargo/config", "clippy.toml", ".rustfmt.toml", "go.mod", "SUPER_REVIEW.md"]) expect(readableSource(path)).toBe(true);
    for (const path of [".cargo/credentials.toml", "config.toml", ".env", "secrets.json", "vendor/Cargo.toml"]) expect(readableSource(path)).toBe(false);
  });

  test("generated Rust headers are recognized without interpreting Rust string contents", () => {
    for (const content of ["// @generated\npub struct A;", "// This file is @generated by prost-build.\npub struct A;", "/* automatically generated by rust-bindgen 0.70 */\npub struct A;"]) expect(generatedSource("x.rs", content)).toBe(true);
    expect(generatedSource("x.rs", 'const TEXT: &str = "// @generated";')).toBe(false);
    expect(generatedSource("x.go", "// Code generated by tool. DO NOT EDIT.\npackage x")).toBe(true);
  });

  test("Rust and Cargo reads stay pinned and preserve mixed-file line identities", async () => {
    const f = fixture({ "src/lib.rs": "pub fn work() {}\n#[cfg(test)]\nmod tests {}\n", "Cargo.toml": '[package]\nname = "app"\nrust-version = "1.70"\n', ".cargo/config.toml": "[build]\n" });
    const receipt = await f.reader.pin(url);
    expect(receipt.files.find(file => file.path === "src/lib.rs")).toMatchObject({ language: "rust", exclusion: undefined });
    f.info.head.sha = "d".repeat(40);
    expect(await f.reader.source(receipt.id, "head", "src/lib.rs", 1, 1)).toMatchObject({ commit: H, content: "1: pub fn work() {}", nextLine: 2, scopeNote: expect.stringContaining("not Rust items") });
    expect(await f.reader.source(receipt.id, "head", "src/lib.rs", 2, 2)).toMatchObject({ content: "2: #[cfg(test)]\n3: mod tests {}", nextLine: null });
    expect(await f.reader.source(receipt.id, "head", "Cargo.toml")).toMatchObject({ commit: H, content: expect.stringContaining("rust-version") });
    expect(await f.reader.source(receipt.id, "head", ".cargo/config.toml")).toMatchObject({ commit: H, exists: true });
    expect(await f.reader.source(receipt.id, "head", ".cargo/credentials.toml")).toMatchObject({ excluded: true });
    expect(f.calls.filter(call => call.includes("/pulls/"))).toHaveLength(1);
  });

  test("mixed-language search is literal, paginated, and excludes known generated/test paths", async () => {
    const files: Record<string, string> = { "adapter.go": "package app\nfunc Work() {}", "src/generated.rs": "// @generated\nfn Work() {}", "tests/smoke.rs": "fn Work() {}" };
    for (let i = 0; i < 21; i++) files["src/f" + i + ".rs"] = "pub fn Work() {}";
    const f = fixture(files);
    const receipt = await f.reader.pin(url);
    let offset: number | null = 0;
    const matches: string[] = [], unread: string[] = [];
    do {
      const page = await f.reader.search(receipt.id, "Work()", "", offset);
      matches.push(...page.matches.map(match => match.path));
      unread.push(...page.unread.map(item => item.path));
      offset = page.nextOffset;
    } while (offset !== null);
    expect(matches).toHaveLength(22);
    expect(matches).toContain("adapter.go");
    expect(matches).not.toContain("tests/smoke.rs");
    expect(unread).toContain("src/generated.rs");
    expect(await f.reader.source(receipt.id, "head", "src/generated.rs")).toMatchObject({ excluded: true });
    expect((await f.reader.search(receipt.id, "Work.*", "src/f1.rs")).matches).toEqual([]);
  });

  test("Rust rule IDs and profile owners resolve without altering the Go namespace", () => {
    const ids: string[] = JSON.parse(readFileSync(resolve(root, "evals/rust/rule-ids.json"), "utf8"));
    const found = lenses.flatMap(name => [...read("references/lenses/rust/" + name + ".md").matchAll(/^## (rust\.[a-z0-9.-]+)$/gm)].map(match => match[1]!));
    expect(found.sort()).toEqual(ids.sort());
    expect(new Set(found).size).toBe(11);
    for (const name of profiles) {
      const text = read("references/profiles/rust/" + name + ".md");
      const owner = /^Owner: (.+)$/m.exec(text)![1];
      const rule = /^Rule: (rust\.[a-z0-9.-]+)$/m.exec(text)![1];
      expect(read("references/lenses/rust/" + owner + ".md")).toContain("## " + rule);
    }
    for (const path of resources) expect(resource.args.path.safeParse(path).success).toBe(true);
    expect(resource.args.path.safeParse("evals/rust/cases.json").success).toBe(false);
    expect(readdirSync(resolve(skill, "references/lenses")).filter(name => name.endsWith(".md"))).toHaveLength(10);
  });

  for (const packageRoot of ["skills/super-review", "adapters/claude/plugin/resources/super-review", "adapters/codex/super-review/skills/super-review"]) {
    test("selective Rust resources are delivered identically by " + packageRoot, async () => {
      const server = await createServer(resolve(root, packageRoot));
      const client = new Client({ name: "rust-resource-test", version: "1" });
      const [serverTransport, clientTransport] = InMemoryTransport.createLinkedPair();
      try {
        await server.connect(serverTransport);
        await client.connect(clientTransport);
        for (const paths of [resources.slice(0, 8), resources.slice(8), ["references/review-contract.md", "references/languages/rust.md", "references/lenses/rust/data-flow.md", "references/profiles/rust/lifecycle-ownership.md", "assets/finding-template.md"]]) {
          const response = await client.callTool({ name: "resources", arguments: { paths } });
          expect(response.isError).not.toBe(true);
          const payload = JSON.parse((response.content as Array<{ text: string }>)[0]!.text) as { resources: Array<{ path: string; content: string }> };
          expect(payload.resources.map(item => item.path)).toEqual(paths);
          for (const item of payload.resources) expect(item.content).toBe(read(item.path));
        }
        expect((await client.callTool({ name: "resources", arguments: { paths: ["evals/rust/cases.json"] } })).isError).toBe(true);
      } finally { await client.close(); await server.close(); }
    });
  }

  test("every evaluator expectation has one separate raw packet", () => {
    const cases = JSON.parse(readFileSync(resolve(root, "evals/rust/cases.json"), "utf8")) as { cases: Array<{ id: string; expect: string[] }> };
    const packet = readFileSync(resolve(root, "evals/rust/packets/idioms.md"), "utf8");
    const sections = [...packet.matchAll(/^## (R\d+)$/gm)].map(match => match[1]);
    expect(sections).toEqual(cases.cases.map(item => item.id));
    expect(new Set(sections).size).toBe(sections.length);
    for (const item of cases.cases) expect(item.expect.length).toBeGreaterThan(0);
  });
});
